# Generated by Django 3.2.8 on 2021-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('phone', models.PositiveBigIntegerField(blank=True, verbose_name='номер телефона')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
            ],
        ),
    ]
